# Generated by Django 3.1.3 on 2020-11-26 17:22

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expens',
            name='date',
            field=models.DateField(default=datetime.date.today(), verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date.today(), verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='income',
            order_with_respect_to='date',
        ),
    ]
