# Generated by Django 3.1.3 on 2020-11-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201126_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expens',
            options={'verbose_name': 'هزینه', 'verbose_name_plural': 'هزینه ها'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'درآمد', 'verbose_name_plural': 'درآمد ها'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='expens',
            order_with_respect_to='date',
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان درآمد')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'عنوان هزینه',
                'verbose_name_plural': 'عناوین هزینه ها',
                'order_with_respect_to': 'title',
            },
        ),
    ]
