# Generated by Django 3.1.3 on 2020-11-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201127_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name': 'عنوان درآمد', 'verbose_name_plural': 'عناوین درآمدها'},
        ),
        migrations.CreateModel(
            name='ExpensCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان هزینه')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'عنوان هزینه',
                'verbose_name_plural': 'عناوین هزینه ها',
                'order_with_respect_to': 'title',
            },
        ),
    ]
