# Generated by Django 3.1.3 on 2020-11-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201127_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='expens',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.expenscategory', verbose_name='گروه هزینه'),
            preserve_default=False,
        ),
    ]
