# Generated by Django 3.1.3 on 2020-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_income_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[(1, 'انصار'), (2, 'سامان'), (3, 'تجارت'), (4, 'مسکن'), (5, 'ملت')], max_length=100, verbose_name='')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('branch_name', models.CharField(max_length=50, verbose_name='')),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
            ],
        ),
    ]
