# Generated by Django 3.1.3 on 2020-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='initial_amount',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='موجودی اولیه '),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(blank=True, default='IR', max_length=26, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(choices=[(1, 'انصار'), (2, 'سامان'), (3, 'تجارت'), (4, 'مسکن'), (5, 'ملت')], max_length=100, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(max_length=50, verbose_name='نام شعبه'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات'),
        ),
    ]
