# Generated by Django 3.1.3 on 2020-11-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201127_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.IntegerField(choices=[(1, 'انصار'), (2, 'سامان'), (3, 'تجارت'), (4, 'مسکن'), (5, 'ملت')], verbose_name='نام بانک'),
        ),
    ]
