# Generated by Django 3.1.3 on 2020-11-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201127_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='expens',
            name='from_bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.bankaccount', verbose_name='برداشت از حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='from_bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.bankaccount', verbose_name='واریز به حساب'),
            preserve_default=False,
        ),
    ]
