# Generated by Django 3.1.3 on 2020-11-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201127_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'شماره حساب', 'verbose_name_plural': 'شماره حسابهای بانکی'},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='from_bank_account',
            new_name='to_bank_account',
        ),
    ]
