# Generated by Django 3.1.3 on 2020-12-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20201202_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marchant',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='bank_accout',
            new_name='bank_account',
        ),
    ]
