# Generated by Django 3.1.3 on 2020-12-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20201202_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان گروه')),
                ('category_type', models.IntegerField(choices=[(1, 'هزینه'), (2, 'درآمد'), (3, 'انتقال')], verbose_name='نوع گروه')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'عنوان هزینه',
                'verbose_name_plural': 'عناوین هزینه ها',
                'order_with_respect_to': 'title',
            },
        ),
    ]
