# Generated by Django 3.1.3 on 2020-12-02 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_transcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcategory',
            options={'verbose_name': 'گروه تراکنش', 'verbose_name_plural': ' گروه تراکنش ها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.transcategory', verbose_name=' گروه'),
        ),
    ]
