# Generated by Django 3.1.3 on 2020-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20201202_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'واریز'), (2, 'برداشت')], default=1, verbose_name='نوع تراکنش'),
        ),
    ]
